name: Build Game
on: 
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5 # Change this to your preferred version

      - name: Install Haxelibs
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel
          haxelib install lime
          haxelib install openfl
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib git hscript https://github.com/HaxeFoundation/hscript

      - name: Configure Lime
        run: |
          haxelib run lime setup
          haxelib run lime setup windows

      - name: Compile Game
        run: haxelib run lime build windows -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: export/release/windows/bin
